### PR TITLE
fix(#831): checkboxes display when user accept or deny cookies

### LINKED ISSUE #831: Cookie consent panel checkboxes don't reflect the state of approbation
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In the cookie consent panel, clicking on buttons to accept or deny all cookies, the state is not reflected in the checkbox

### Reduced test cases

Go to https://boosted.orange.com/ in incognito mode.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.1.1

### PR DESCRIPTION
**Pull request by MewenLeHo**
Closes #831

### CODE REVIEW

File: site/assets/js/tac.js [hunk 1]
```diff
@@ -44,13 +44,45 @@
...
+        .createRange()
+        .createContextualFragment(
+          '<div class="form-check form-switch my-2 my-lg-0"><input class="form-check-input ms-0" type="checkbox" id="googletagmanagerAllowed" aria-describedby="tacCLgoogletagmanager" onchange="' +
+            choiceEvent +
+            '"><label class="form-check-label visually-hidden" for="googletagmanagerAllowed">Google Tag Manager</label></div>'
+        )
+      ask.innerHTML = ''
+      ask.append(toggle)
+
+      var allowConsentButton = document.querySelector('#tarteaucitronAllAllowed')
```
Comment (julien-deramond) [inline site/assets/js/tac.js:65]: The following code (from here until line 85) is triggered by 'googletagmanager_added'. It is OK for now because we handle only one service. Isn't there another way to trigger it? Something more general?

**Review by julien-deramond — CHANGES_REQUESTED** [review]
In addition, if

- I authorize all cookies in the bottom panel
- I go to http://localhost:9001/docs/5.1/about/cookies/

Google Tag Manager is well authorized but the checkbox isn't checked

File: site/assets/js/tac.js [hunk 2]
```diff
@@ -44,13 +44,51 @@
...
+            choiceEvent +
+            '"><label class="form-check-label visually-hidden" for="googletagmanagerAllowed">Google Tag Manager</label></div>'
+        )
+      ask.innerHTML = ''
+      ask.append(toggle)
+    },
+    { once: true }
+  )
+
+  window.addEventListener(
```
Comment (julien-deramond) [inline site/assets/js/tac.js:68]: This listener already exists at line 41, can't you put the both function content into the same `window.addEventListener('tac.open_panel', function()`?

**Review by julien-deramond — CHANGES_REQUESTED** [review]
`package-lock.json` is commited and shouldn't be.

**Comment by julien-deramond** [comment]
> In addition, if
> 
>     * I authorize all cookies in the bottom panel
> 
>     * I go to http://localhost:9001/docs/5.1/about/cookies/
> 
> 
> Google Tag Manager is well authorized but the checkbox isn't checked

If it is too complicated to tackle in this PR, you can create another issue.
